spring:
    #zipkin的采样率
  sleuth:
    sampler:
      percentage: 1.0
  #rabbitmq配置
  rabbitmq:
    host: 10.109.10.190
    port: 5672
    username: oms
    password: 123456

#=================================数据库配置开始===================
  #jpa配置
  #jpa:
  #  show-sql: true
  #  hibernate:
  #    ddl-auto: none
  #数据源配置
  datasource:
    #执行的建表语句
    #schema: classpath:schema.sql
    #执行的sql语句
    #data: classpath:data.sql
    #主配置
    url: jdbc:oracle:thin:@10.109.10.190:1521:oms
    username: oms_sys_dev
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
    #其它配置
    #platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 30
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 缓存配置
  redis:
    database: 0
    host: 10.109.10.190
    port: 6379
    password: 123456
    pool:
      max-active: 8 
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
#自定义配置开始  -- 组织机构同步配置参数   
      
#=================================Feign配置开始======================
#启用hystrix
feign:
  hystrix:
    enabled: true
  #启用压缩
  compression:
    request:
      #压缩的类型
      mime-types: application/json
      #压缩阀值，1k
      min-request-size: 1024

#针对每个服务设置ribbon超时和请求重试
#crm-service-user:
#  ribbon:
#    ConnectTimeout: 500
#    ReadTimeout: 3000
#    OkToRetryOnAllOperation: true
#    MaxAutoRetries: 5
#    MaxAutoRetriesNextServer: 2

#关闭超时检查,否则第一次的服务间请求会失败
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
#=================================Feign配置结束======================



#=================================默认配置开始，不用修改===================
#设置actuator开关
management:
  security:
    enabled: false

#crm自定义配置
oms:
  #controller/service/repository的日志打印功能
  log:
    #是否启用
    enabled: true
  #swagger程序文档功能
  swagger:
    #是否启用
    enabled: true
    #controller包位置
    base-package: com.tark.oms.controller
    title: 系统管理接口文档
    description: 主要包含字典管理、角色管理等
    version: V1.0
    
securityDefinitions:
  APIKey:
    type: apiKey
    name: Authorization
    in: header
security:
  - APIKey: []    
#=================================默认配置结束，不用修改===================


#=================================数据库配置结束===================

#==============================mybatis驼峰式类名自动映射数据库字段=============================
mybatis:
    configuration:
      map-underscore-to-camel-case: true
    type-aliases-package: com.tark.oms.beans
    mapper-locations: classpath:com/tark/oms/dao/mapper/*.xml

mapper:
    mappers:
        - com.tark.oms.common.mybatis.BaseInfoMapper
    not-empty: false
    identity: ORACLE
    # 写入之前
    ORDER: BEFORE

pagehelper:
    helperDialect: oracle
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
